#ifndef MQUICKJS_INTERNAL_H
#define MQUICKJS_INTERNAL_H

#include "mquickjs_priv.h"
#include "mquickjs_atom.h"

#define __exception __attribute__((warn_unused_result))

#define JS_STACK_SLACK  16   /* additional free space on the stack */
/* min free size in bytes between heap_free and the bottom of the stack */
#define JS_MIN_FREE_SIZE 512
/* minimum free size in bytes to create the out of memory object */
#define JS_MIN_CRITICAL_FREE_SIZE (JS_MIN_FREE_SIZE - 256)
#define JS_MAX_LOCAL_VARS 65535
#define JS_MAX_FUNC_STACK_SIZE 65535
#define JS_MAX_ARGC 65535
/* maximum number of recursing JS_Call() */
#define JS_MAX_CALL_RECURSE 8


#define JS_VALUE_IS_BOTH_INT(a, b) ((((a) | (b)) & 1) == 0)
#define JS_VALUE_IS_BOTH_SHORT_FLOAT(a, b) (((((a) - JS_TAG_SHORT_FLOAT) | ((b) - JS_TAG_SHORT_FLOAT)) & 7) == 0)
/* function call flags (max 31 bits) */
#define FRAME_CF_ARGC_MASK      0xffff
/* FRAME_CF_CTOR */
#define FRAME_CF_POP_RET        (1 << 17) /* pop the return value */
#define FRAME_CF_PC_ADD1        (1 << 18) /* increment the PC by 1 instead of 3 */

#define JS_MB_PAD(n)  (JSW * 8 - (n))

typedef struct {
    JS_MB_HEADER;
    JSWord dummy: JS_MB_PAD(JS_MTAG_BITS);
} JSMemBlockHeader;

typedef struct {
    JS_MB_HEADER;
    /* in JSWords excluding the header. Free blocks of JSW bytes
       are only generated by js_shrink() and may not be always
       compacted */
    JSWord size: JS_MB_PAD(JS_MTAG_BITS);
} JSFreeBlock;

#if JSW == 8
#define JS_STRING_LEN_MAX 0x7ffffffe
#else
#define JS_STRING_LEN_MAX ((1 << (32 - JS_MTAG_BITS - 3)) - 1)
#endif

typedef struct {
    JS_MB_HEADER;
    JSWord is_unique: 1;
    JSWord is_ascii: 1;
    /* true if the string content represents a number, only meaningful
       is is_unique = true */
    JSWord is_numeric: 1;
    JSWord len: JS_MB_PAD(JS_MTAG_BITS + 3);
    uint8_t buf[];
} JSString;

typedef struct {
    JSWord string_buf[sizeof(JSString) / sizeof(JSWord)]; /* for JSString */
    uint8_t buf[5];
} JSStringCharBuf;

#define JS_BYTE_ARRAY_SIZE_MAX ((1 << (32 - JS_MTAG_BITS)) - 1)

typedef struct {
    JS_MB_HEADER;
    JSWord size: JS_MB_PAD(JS_MTAG_BITS);
    uint8_t buf[];
} JSByteArray;

#define JS_VALUE_ARRAY_SIZE_MAX ((1 << (32 - JS_MTAG_BITS)) - 1)

typedef struct {
    JS_MB_HEADER;
    JSWord size: JS_MB_PAD(JS_MTAG_BITS);
    JSValue arr[];
} JSValueArray;

typedef struct JSVarRef {
    JS_MB_HEADER;
    JSWord is_detached : 1;
    JSWord dummy: JS_MB_PAD(JS_MTAG_BITS + 1);
    union {
        JSValue value; /* is_detached = true */
        struct {
            JSValue next; /* is_detached = false: JS_NULL or JSVarRef,
                             must be at the same address as 'value' */
            JSValue *pvalue;
        };
    } u;
} JSVarRef;

typedef struct {
    JS_MB_HEADER;
    JSWord dummy: JS_MB_PAD(JS_MTAG_BITS);
#ifdef JS_PTR64
    struct {
        double dval;
    } u;
#else
    /* unaligned 64 bit access in 32-bit mode */
    struct __attribute__((packed)) {
        double dval;
    } u;
#endif
} JSFloat64;

typedef struct JSROMClass {
    JS_MB_HEADER;
    JSWord dummy: JS_MB_PAD(JS_MTAG_BITS);
    JSValue props;
    int32_t ctor_idx; /* -1 if defining a normal object */
    JSValue proto_props;
    JSValue parent_class; /* JSROMClass or JS_NULL */
} JSROMClass;

#define N_ROM_ATOM_TABLES_MAX 2

/* must be large enough to have a negligible runtime cost and small
   enough to call the interrupt callback often. */
#define JS_INTERRUPT_COUNTER_INIT 10000

#define JS_STRING_POS_CACHE_SIZE 2
#define JS_STRING_POS_CACHE_MIN_LEN 16 

typedef enum {
    POS_TYPE_UTF8,
    POS_TYPE_UTF16,
} StringPosTypeEnum;

typedef struct {
    JSValue str; /* JS_NULL or weak reference to a JSString. It
                    contains at least JS_STRING_POS_CACHE_MIN_LEN
                    bytes and is a non ascii string */
    uint32_t str_pos[2]; /* 0 = UTF-8 pos (in bytes), 1 = UTF-16 pos */
} JSStringPosCacheEntry;

struct JSContext {
    /* memory map:
       Stack
       Free area
       Heap
       JSContext
    */
    uint8_t *heap_base;
    uint8_t *heap_free; /* first free area */
    uint8_t *stack_top;
    JSValue *stack_bottom; /* sp must always be higher than stack_bottom */
    JSValue *sp; /* current stack pointer */
    JSValue *fp; /* current frame pointer, stack_top if none */
    uint32_t min_free_size; /* min free size between heap_free and the
                               bottom of the stack */
    BOOL in_out_of_memory : 8; /* != 0 if generating the out of memory object */
    uint8_t n_rom_atom_tables;
    uint8_t string_pos_cache_counter; /* used for string_pos_cache[] update */
    uint16_t class_count; /* number of classes including user classes */
    int16_t interrupt_counter;
    BOOL current_exception_is_uncatchable : 8;
    struct JSParseState *parse_state; /* != NULL during JS_Eval() */
    int unique_strings_len;
    int js_call_rec_count; /* number of recursing JS_Call() */
    JSGCRef *top_gc_ref; /* used to reference temporary GC roots (stack top) */
    JSGCRef *last_gc_ref; /* used to reference temporary GC roots (list) */
    const JSWord *atom_table; /* constant atom table */
    /* 'n_rom_atom_tables' atom tables from code loaded from rom */
    const JSValueArray *rom_atom_tables[N_ROM_ATOM_TABLES_MAX];
    const JSCFunctionDef *c_function_table;
    const JSCFinalizer *c_finalizer_table;
    uint64_t random_state;
    JSInterruptHandler *interrupt_handler;
    JSWriteFunc *write_func; /* for the various dump functions */
    void *opaque;
    JSValue *class_obj; /* same as class_proto + class_count */
    JSStringPosCacheEntry string_pos_cache[JS_STRING_POS_CACHE_SIZE];
                                           
    /* must only contain JSValue from this point (see JS_GC()) */
    JSValue unique_strings; /* JSValueArray of sorted strings or JS_NULL */
    
    JSValue current_exception; /* currently pending exception, must
                                  come after unique_strings */
#ifdef DEBUG_GC
    JSValue dummy_block; /* dummy memory block near the start of the memory */
#endif
    JSValue empty_props; /* empty prop list, for objects with no properties */
    JSValue global_obj;
    JSValue minus_zero; /* minus zero float64 value */
    JSValue class_proto[]; /* prototype for each class (class_count
                              element, then class_count elements for
                              class_obj */
};

typedef enum {
    JS_VARREF_KIND_ARG, /* var_idx is an argument of the parent function */
    JS_VARREF_KIND_VAR, /* var_idx is a local variable of the parent function */
    JS_VARREF_KIND_VAR_REF, /* var_idx is a var ref of the parent function */
    JS_VARREF_KIND_GLOBAL, /* to debug */
} JSVarRefKindEnum;

typedef struct JSObject JSObject;

typedef struct {
    /* string, short integer or JS_UNINITIALIZED if no property. If
       the last property is uninitialized, hash_next = 2 *
       first_free. */
    JSValue key;
    /* JS_PROP_GETSET: JSValueArray of two elements
       JS_PROP_VARREF: JSVarRef */
    JSValue value;
    /* XXX: when JSW = 8, could use 32 bits for hash_next (faster) */
    uint32_t hash_next : 30;  /* low bit at zero */
    uint32_t prop_type : 2;
} JSProperty;

typedef struct {
    JSValue func_bytecode; /* JSFunctionBytecode */
    JSValue var_refs[]; /* JSValueArray */
} JSClosureData;

typedef struct {
    uint32_t idx;
    JSValue params; /* optional associated parameters */
} JSCFunctionData;
    
typedef struct {
    JSValue tab; /* JS_NULL or JSValueArray */
    uint32_t len; /* maximum value: 2^30-1 */
} JSArrayData;

typedef struct {
    JSValue message; /* string or JS_NULL */
    JSValue stack; /* string or JS_NULL */
} JSErrorData;
    
typedef struct {
    JSValue byte_buffer; /* JSByteBuffer */
} JSArrayBuffer;

typedef struct {
    JSValue buffer; /* corresponding array buffer */
    uint32_t len; /* in elements */
    uint32_t offset; /* in elements */
} JSTypedArray;

typedef struct {
    JSValue source;
    JSValue byte_code;
    int last_index;
} JSRegExp;

typedef struct
#ifndef JS_PTR64
__attribute__((packed)) /* unaligned 64 bit access in 32-bit mode */
#endif
{
    double dval;
} JSDate;

typedef struct {
    void *opaque;
} JSObjectUserData;

struct JSObject {
    JS_MB_HEADER;
    JSWord class_id: 8;
    JSWord extra_size: JS_MB_PAD(JS_MTAG_BITS + 8);  /* object additional size, in JSValue */

    JSValue proto; /* JSObject or JS_NULL */
    /* JSValueArray. structure:
       prop_count (number of properties excluding deleted ones)
       hash_mask (= hash_size - 1)
       hash_table[hash_size] (0 = end of list or offset in array)
       JSProperty props[]
    */
    JSValue props;
    /* number of additional fields depends on the object */
    union {
        JSClosureData closure;
        JSCFunctionData cfunc;
        JSArrayData array;
        JSErrorData error;
        JSArrayBuffer array_buffer;
        JSTypedArray typed_array;
        JSRegExp regexp;
        JSDate date;
        JSObjectUserData user;
    } u;
};

typedef struct JSFunctionBytecode {
    JS_MB_HEADER;
    JSWord has_arguments : 1; /* only used during parsing */
    JSWord has_local_func_name : 1; /* only used during parsing */
    JSWord has_column : 1; /* column debug info is present */
    /* during parse: variable index + 1 of hoisted function, 0 otherwise */
    JSWord arg_count : 16; 
    JSWord dummy: JS_MB_PAD(JS_MTAG_BITS + 3 + 16);

    JSValue func_name; /* JS_NULL if anonymous function */
    JSValue byte_code; /* JS_NULL if the function is not parsed yet */
    JSValue cpool; /* constant pool */
    JSValue vars; /* only for debug */
    JSValue ext_vars; /* records of (var_name, var_kind (2 bits) var_idx (16 bits)) */
    uint16_t stack_size; /* maximum stack size */
    uint16_t ext_vars_len; /* XXX: only used during parsing */
    JSValue filename; /* filename in which the function is defined */
    JSValue pc2line; /* JSByteArray or JS_NULL if not initialized */
    uint32_t source_pos; /* only used during parsing (XXX: shrink) */
} JSFunctionBytecode;
typedef enum OPCodeFormat {
#define FMT(f) OP_FMT_ ## f,
#define DEF(id, size, n_pop, n_push, f)
#include "mquickjs_opcode.h"
#undef DEF
#undef FMT
} OPCodeFormat;

typedef enum OPCodeEnum {
#define FMT(f)
#define DEF(id, size, n_pop, n_push, f) OP_ ## id,
#define def(id, size, n_pop, n_push, f)
#include "mquickjs_opcode.h"
#undef def
#undef DEF
#undef FMT
    OP_COUNT,
} OPCodeEnum;

typedef struct {
#ifdef DUMP_BYTECODE
    const char *name;
#endif
    uint8_t size; /* in bytes */
    /* the opcodes remove n_pop items from the top of the stack, then
       pushes n_pusch items */
    uint8_t n_pop;
    uint8_t n_push;
    uint8_t fmt;
} JSOpCode;

#define JS_SHORTINT_MIN (-(1 << 30))
#define JS_SHORTINT_MAX ((1 << 30) - 1)
typedef struct {
    JSGCRef buffer_ref; /* string, JSByteBuffer or JS_EXCEPTION */
    int len; /* current string length (in bytes) */
    BOOL is_ascii;
} StringBuffer;

enum {
    TOK_NUMBER = 128,
    TOK_STRING,
    TOK_IDENT,
    TOK_REGEXP,
    /* warning: order matters (see js_parse_assign_expr) */
    TOK_MUL_ASSIGN, 
    TOK_DIV_ASSIGN, 
    TOK_MOD_ASSIGN, 
    TOK_PLUS_ASSIGN, 
    TOK_MINUS_ASSIGN,
    TOK_SHL_ASSIGN,
    TOK_SAR_ASSIGN,
    TOK_SHR_ASSIGN,
    TOK_AND_ASSIGN,
    TOK_XOR_ASSIGN,
    TOK_OR_ASSIGN,
    TOK_POW_ASSIGN,
    TOK_DEC,
    TOK_INC,
    TOK_SHL,
    TOK_SAR,
    TOK_SHR,
    TOK_LT,
    TOK_LTE,
    TOK_GT,
    TOK_GTE,
    TOK_EQ,
    TOK_STRICT_EQ,
    TOK_NEQ,
    TOK_STRICT_NEQ,
    TOK_LAND,
    TOK_LOR,
    TOK_POW,
    TOK_EOF,
    /* keywords */
    TOK_FIRST_KEYWORD,
    TOK_NULL = TOK_FIRST_KEYWORD + JS_ATOM_null,
    TOK_FALSE = TOK_FIRST_KEYWORD + JS_ATOM_false,
    TOK_TRUE = TOK_FIRST_KEYWORD + JS_ATOM_true,
    TOK_IF = TOK_FIRST_KEYWORD + JS_ATOM_if,
    TOK_ELSE = TOK_FIRST_KEYWORD + JS_ATOM_else,
    TOK_RETURN = TOK_FIRST_KEYWORD + JS_ATOM_return,
    TOK_VAR = TOK_FIRST_KEYWORD + JS_ATOM_var,
    TOK_THIS = TOK_FIRST_KEYWORD + JS_ATOM_this,
    TOK_DELETE = TOK_FIRST_KEYWORD + JS_ATOM_delete,
    TOK_VOID = TOK_FIRST_KEYWORD + JS_ATOM_void,
    TOK_TYPEOF = TOK_FIRST_KEYWORD + JS_ATOM_typeof,
    TOK_NEW = TOK_FIRST_KEYWORD + JS_ATOM_new,
    TOK_IN = TOK_FIRST_KEYWORD + JS_ATOM_in,
    TOK_INSTANCEOF = TOK_FIRST_KEYWORD + JS_ATOM_instanceof,
    TOK_DO = TOK_FIRST_KEYWORD + JS_ATOM_do,
    TOK_WHILE = TOK_FIRST_KEYWORD + JS_ATOM_while,
    TOK_FOR = TOK_FIRST_KEYWORD + JS_ATOM_for,
    TOK_BREAK = TOK_FIRST_KEYWORD + JS_ATOM_break,
    TOK_CONTINUE = TOK_FIRST_KEYWORD + JS_ATOM_continue,
    TOK_SWITCH = TOK_FIRST_KEYWORD + JS_ATOM_switch,
    TOK_CASE = TOK_FIRST_KEYWORD + JS_ATOM_case,
    TOK_DEFAULT = TOK_FIRST_KEYWORD + JS_ATOM_default,
    TOK_THROW = TOK_FIRST_KEYWORD + JS_ATOM_throw,
    TOK_TRY = TOK_FIRST_KEYWORD + JS_ATOM_try,
    TOK_CATCH = TOK_FIRST_KEYWORD + JS_ATOM_catch,
    TOK_FINALLY = TOK_FIRST_KEYWORD + JS_ATOM_finally,
    TOK_FUNCTION = TOK_FIRST_KEYWORD + JS_ATOM_function,
    TOK_DEBUGGER = TOK_FIRST_KEYWORD + JS_ATOM_debugger,
    TOK_WITH = TOK_FIRST_KEYWORD + JS_ATOM_with,
    TOK_CLASS = TOK_FIRST_KEYWORD + JS_ATOM_class,
    TOK_CONST = TOK_FIRST_KEYWORD + JS_ATOM_const,
    TOK_ENUM = TOK_FIRST_KEYWORD + JS_ATOM_enum,
    TOK_EXPORT = TOK_FIRST_KEYWORD + JS_ATOM_export,
    TOK_EXTENDS = TOK_FIRST_KEYWORD + JS_ATOM_extends,
    TOK_IMPORT = TOK_FIRST_KEYWORD + JS_ATOM_import,
    TOK_SUPER = TOK_FIRST_KEYWORD + JS_ATOM_super,
    TOK_IMPLEMENTS = TOK_FIRST_KEYWORD + JS_ATOM_implements,
    TOK_INTERFACE = TOK_FIRST_KEYWORD + JS_ATOM_interface,
    TOK_LET = TOK_FIRST_KEYWORD + JS_ATOM_let,
    TOK_PACKAGE = TOK_FIRST_KEYWORD + JS_ATOM_package,
    TOK_PRIVATE = TOK_FIRST_KEYWORD + JS_ATOM_private,
    TOK_PROTECTED = TOK_FIRST_KEYWORD + JS_ATOM_protected,
    TOK_PUBLIC = TOK_FIRST_KEYWORD + JS_ATOM_public,
    TOK_STATIC = TOK_FIRST_KEYWORD + JS_ATOM_static,
    TOK_YIELD = TOK_FIRST_KEYWORD + JS_ATOM_yield,
};

/* this structure is pushed on the JS stack, so all members must be JSValue */
typedef struct BlockEnv {
    JSValue prev; /* JS_NULL or stack index */
    JSValue label_name; /* JS_NULL if none */
    JSValue label_break;
    JSValue label_cont;
    JSValue label_finally;
    JSValue drop_count; /* (int) number of stack elements to drop */
} BlockEnv;

typedef uint32_t JSSourcePos;

typedef struct JSToken {
    int val;
    JSSourcePos source_pos; /* position in source */
    union {
        double d; /* TOK_NUMBER */
        struct {
            uint32_t re_flags; /* regular expression flags */
            uint32_t re_end_pos; /* at the final '/' */
        } regexp;
    } u;
    JSValue value; /* associated value: string for TOK_STRING, TOK_REGEXP;
                      identifier for TOK_IDENT or keyword */
} JSToken;

typedef struct JSParseState {
    JSContext *ctx;
    JSToken token;

    BOOL got_lf : 8; /* true if got line feed before the current token */
    /* global eval: variables are defined as global */
    BOOL is_eval : 8;
    /* if true, return the last value. */
    BOOL has_retval : 8;
    /* if true, implicitly define global variables in an
       assignment. */
    BOOL is_repl : 8;
    BOOL has_column : 8; /* column debug info is present */
    /* TRUE if the expression result has been dropped (see PF_DROP) */
    BOOL dropped_result : 8;
    JSValue source_str; /* source string or JS_NULL */
    JSValue filename_str; /* 'filename' converted to string */
    /* zero terminated source buffer. Automatically updated by the GC
       if source_str is a string */
    const uint8_t *source_buf; 
    uint32_t buf_pos;
    uint32_t buf_len;

    /* current function */
    JSValue cur_func;
    JSValue byte_code;
    uint32_t byte_code_len;
    int last_opcode_pos; /* -1 if no last opcode */
    int last_pc2line_pos; /* pc2line pos for the last opcode */
    JSSourcePos last_pc2line_source_pos;
    
    uint32_t pc2line_bit_len;
    JSSourcePos pc2line_source_pos; /* last generated source pos */
    
    uint16_t cpool_len;
    /* size of the byte code necessary to define the hoisted functions  */
    uint32_t hoisted_code_len;
    
    /* argument + defined local variable count */
    uint16_t local_vars_len;
    
    int eval_ret_idx; /* variable index for the eval return value, -1
                         if no return value */
    JSValue top_break; /* JS_NULL or SP_TO_VALUE(BlockEnv *) */

    /* regexp parsing only */
    uint8_t capture_count;
    uint8_t re_in_js: 1;
    uint8_t multi_line : 1;
    uint8_t dotall : 1;
    uint8_t ignore_case : 1;
    uint8_t is_unicode : 1;

    /* error handling */
    jmp_buf jmp_env;
    char error_msg[64];
} JSParseState;
typedef struct JSParsePos {
    BOOL got_lf : 8;
    BOOL regexp_allowed : 8;
    uint32_t source_pos;
} JSParsePos;
typedef enum {
    JS_PARSE_FUNC_STATEMENT,
    JS_PARSE_FUNC_EXPR,
    JS_PARSE_FUNC_METHOD,
} JSParseFunctionEnum;
typedef enum {
    PUT_LVALUE_KEEP_TOP,  /* [depth] v -> v */
    PUT_LVALUE_NOKEEP_TOP, /* [depth] v -> */
    PUT_LVALUE_KEEP_SECOND, /* [depth] v0 v -> v0 */
    PUT_LVALUE_NOKEEP_BOTTOM, /* v [depth] -> */
} PutLValueEnum;
typedef enum {
    PARSE_FUNC_js_parse_expr_comma,
    PARSE_FUNC_js_parse_assign_expr,
    PARSE_FUNC_js_parse_cond_expr,
    PARSE_FUNC_js_parse_logical_and_or,
    PARSE_FUNC_js_parse_expr_binary,
    PARSE_FUNC_js_parse_unary,
    PARSE_FUNC_js_parse_postfix_expr,
    PARSE_FUNC_js_parse_statement,
    PARSE_FUNC_js_parse_block,
    PARSE_FUNC_js_parse_json_value,
    PARSE_FUNC_re_parse_alternative,
    PARSE_FUNC_re_parse_disjunction,
} ParseExprFuncEnum;

typedef int JSParseFunc(JSParseState *s, int state, int param);
typedef struct {
    uint16_t new_var_idx; /* new local var index */
    uint8_t is_local;
} ConvertVarEntry;
typedef struct {
    JSContext *ctx;
    JSValue *gsp;
    JSValue *gs_bottom;
    JSValue *gs_top;
    BOOL overflow;
} GCMarkState;
typedef struct {
    JSContext *ctx;
    uintptr_t offset;
    BOOL update_atoms;
} BCRelocState;
#define PARSE_STATE_INIT 0xfe
#define PARSE_STATE_RET  0xff
#define PARSE_PUSH_INT(s, v) js_parse_push_val(s, JS_NewShortInt(v))
#define PARSE_POP_INT(s, v) v = JS_VALUE_GET_INT(js_parse_pop_val(s))

#define PARSE_START1()                          \
    switch(state) {\
    case PARSE_STATE_INIT: break;\
    default: abort();\
    case 0: goto parse_state0;\
    }

#define PARSE_START2()                          \
    switch(state) {\
    case PARSE_STATE_INIT: break;\
    default: abort();\
    case 0: goto parse_state0;\
    case 1: goto parse_state1;\
    }

#define PARSE_START3()                          \
    switch(state) {\
    case PARSE_STATE_INIT: break;\
    default: abort();\
    case 0: goto parse_state0;\
    case 1: goto parse_state1;\
    case 2: goto parse_state2;\
    }

#define PARSE_START7()                          \
    switch(state) {\
    case PARSE_STATE_INIT: break;\
    default: abort();\
    case 0: goto parse_state0;\
    case 1: goto parse_state1;\
    case 2: goto parse_state2;\
    case 3: goto parse_state3;                  \
    case 4: goto parse_state4;\
    case 5: goto parse_state5;\
    case 6: goto parse_state6;\
    }

#define PARSE_START12()                          \
    switch(state) {\
    case PARSE_STATE_INIT: break;\
    default: abort();\
    case 0: goto parse_state0;\
    case 1: goto parse_state1;\
    case 2: goto parse_state2;\
    case 3: goto parse_state3;                  \
    case 4: goto parse_state4;\
    case 5: goto parse_state5;\
    case 6: goto parse_state6;\
    case 7: goto parse_state7;                  \
    case 8: goto parse_state8;\
    case 9: goto parse_state9;\
    case 10: goto parse_state10;\
    case 11: goto parse_state11;\
    }

/* WARNING: local variables are not preserved across PARSE_CALL(). So
   they must be explicitly saved and restored */
#define PARSE_CALL(s, cur_state, func, param) return (cur_state | (PARSE_FUNC_ ## func << 8) | ((param) << 16)); parse_state ## cur_state : ;

/* preserve var1, ... across the call */
#define PARSE_CALL_SAVE1(s, cur_state, func, param, var1) \
    PARSE_PUSH_INT(s, var1);                                    \
    PARSE_CALL(s, cur_state, func, param);                      \
    PARSE_POP_INT(s, var1);

#define PARSE_CALL_SAVE2(s, cur_state, func, param, var1, var2) \
    PARSE_PUSH_INT(s, var1);                                    \
    PARSE_PUSH_INT(s, var2);                                    \
    PARSE_CALL(s, cur_state, func, param);                      \
    PARSE_POP_INT(s, var2);                                     \
    PARSE_POP_INT(s, var1);

#define PARSE_CALL_SAVE3(s, cur_state, func, param, var1, var2, var3)        \
    PARSE_PUSH_INT(s, var1);                                    \
    PARSE_PUSH_INT(s, var2);                                    \
    PARSE_PUSH_INT(s, var3);                                    \
    PARSE_CALL(s, cur_state, func, param);                      \
    PARSE_POP_INT(s, var3);                                     \
    PARSE_POP_INT(s, var2);                                     \
    PARSE_POP_INT(s, var1);

#define PARSE_CALL_SAVE4(s, cur_state, func, param, var1, var2, var3, var4)  \
    PARSE_PUSH_INT(s, var1);                                    \
    PARSE_PUSH_INT(s, var2);                                    \
    PARSE_PUSH_INT(s, var3);                                    \
    PARSE_PUSH_INT(s, var4);                                    \
    PARSE_CALL(s, cur_state, func, param);                      \
    PARSE_POP_INT(s, var4);                                     \
    PARSE_POP_INT(s, var3);                                     \
    PARSE_POP_INT(s, var2);                                     \
    PARSE_POP_INT(s, var1);

#define PARSE_CALL_SAVE5(s, cur_state, func, param, var1, var2, var3, var4, var5) \
    PARSE_PUSH_INT(s, var1);                                    \
    PARSE_PUSH_INT(s, var2);                                    \
    PARSE_PUSH_INT(s, var3);                                    \
    PARSE_PUSH_INT(s, var4);                                    \
    PARSE_PUSH_INT(s, var5);                                    \
    PARSE_CALL(s, cur_state, func, param);                      \
    PARSE_POP_INT(s, var5);                                     \
    PARSE_POP_INT(s, var4);                                     \
    PARSE_POP_INT(s, var3);                                     \
    PARSE_POP_INT(s, var2);                                     \
    PARSE_POP_INT(s, var1);

#define PARSE_CALL_SAVE6(s, cur_state, func, param, var1, var2, var3, var4, var5, var6) \
    PARSE_PUSH_INT(s, var1);                                    \
    PARSE_PUSH_INT(s, var2);                                    \
    PARSE_PUSH_INT(s, var3);                                    \
    PARSE_PUSH_INT(s, var4);                                    \
    PARSE_PUSH_INT(s, var5);                                    \
    PARSE_PUSH_INT(s, var6);                                    \
    PARSE_CALL(s, cur_state, func, param);                      \
    PARSE_POP_INT(s, var6);                                     \
    PARSE_POP_INT(s, var5);                                     \
    PARSE_POP_INT(s, var4);                                     \
    PARSE_POP_INT(s, var3);                                     \
    PARSE_POP_INT(s, var2);                                     \
    PARSE_POP_INT(s, var1);

#define SKIP_HAS_ARGUMENTS (1 << 0)
#define SKIP_HAS_FUNC_NAME (1 << 1)
#define SKIP_HAS_SEMI (1 << 2)
#define LRE_FLAG_GLOBAL (1 << 0)
#define LABEL_RESOLVED_FLAG (1 << 29)
#define LABEL_OFFSET_MASK ((1 << 29) - 1)
#define LABEL_NONE JS_NewShortInt(-1)
#define JS_DEF_PROP_LOOKUP  (1 << 0)
#define JS_DEF_PROP_RET_VAL (1 << 1)
#define JS_DEF_PROP_HAS_VALUE (1 << 2)
#define JS_DEF_PROP_HAS_GET   (1 << 3)
#define JS_DEF_PROP_HAS_SET   (1 << 4)
#define SP_TO_VALUE(ctx, fp) JS_NewShortInt((uint8_t *)(fp) - (uint8_t *)ctx)
#define VALUE_TO_SP(ctx, val) (void *)((uint8_t *)ctx + JS_VALUE_GET_INT(val))
typedef enum {
#define REDEF(id, size) REOP_ ## id,
#include "mquickjs_opcode.h"
#undef REDEF
    REOP_COUNT,
} REOPCodeEnum;

#define CAPTURE_COUNT_MAX 255
#define REGISTER_COUNT_MAX 255

typedef struct {
#ifdef DUMP_REOP
    const char *name;
#endif
    uint8_t size;
} REOpCode;
#define LRE_FLAG_IGNORECASE (1 << 1)
#define LRE_FLAG_MULTILINE  (1 << 2)
#define LRE_FLAG_DOTALL     (1 << 3)
#define LRE_FLAG_UNICODE    (1 << 4)
#define LRE_FLAG_STICKY     (1 << 5)

#define RE_HEADER_FLAGS          0
#define RE_HEADER_CAPTURE_COUNT  2
#define RE_HEADER_REGISTER_COUNT 3

#define RE_HEADER_LEN 4

#define CLASS_RANGE_BASE 0x40000000

typedef enum {
    CHAR_RANGE_d,
    CHAR_RANGE_D,
    CHAR_RANGE_s,
    CHAR_RANGE_S,
    CHAR_RANGE_w,
    CHAR_RANGE_W,
} CharRangeEnum;

/* inline helpers (included by all engine TUs) */
static force_inline JSValue JS_NewTailCall(int val)
{
    return JS_VALUE_MAKE_SPECIAL(JS_TAG_EXCEPTION, JS_EX_CALL + val);
}
static force_inline BOOL JS_IsIntOrShortFloat(JSValue val)
{
#ifdef JS_USE_SHORT_FLOAT
    return JS_IsInt(val) || JS_IsShortFloat(val);
#else
    return JS_IsInt(val);
#endif
}
static force_inline int utf8_char_len(int c)
{
    int l;
    if (c < 0x80) {
        l = 1;
    } else if (c < 0xc0) {
        l = 1;
    } else if (c < 0xe0) {
        l = 2;
    } else if (c < 0xf0) {
        l = 3;
    } else if (c < 0xf8) {
        l = 4;
    } else {
        l = 1;
    }
    return l;
}
static inline uint32_t hash_prop(JSValue prop)
{
    return (prop / JSW) ^ (prop % JSW); /* XXX: improve */
}

/* return NULL if not found */
static force_inline JSProperty *find_own_property_inlined(JSContext *ctx,
                                                          JSObject *p, JSValue prop)
{
    JSValueArray *arr;
    JSProperty *pr;
    uint32_t hash_mask, h, idx;
    
    arr = JS_VALUE_TO_PTR(p->props);
    hash_mask = JS_VALUE_GET_INT(arr->arr[1]);
    h = hash_prop(prop) & hash_mask;
    idx = arr->arr[2 + h]; /* JSValue, hence idx * 2 */
    while (idx != 0) {
        pr = (JSProperty *)((uint8_t *)arr->arr + idx * (sizeof(JSValue) / 2));
        if (pr->key == prop)
            return pr;
        idx = pr->hash_next; /* JSValue, hence idx * 2 */
    }
    return NULL;
}
static force_inline BOOL unicode_is_space_ascii(uint32_t c)
{
    return (c >= 0x0009 && c <= 0x000D) || (c == 0x0020);
}

static BOOL unicode_is_space_non_ascii(uint32_t c)
{
    return (c == 0x00A0 ||
            c == 0x1680 ||
            (c >= 0x2000 && c <= 0x200A) ||
            (c >= 0x2028 && c <= 0x2029) ||
            c == 0x202F ||
            c == 0x205F ||
            c == 0x3000 ||
            c == 0xFEFF);
}

static force_inline BOOL unicode_is_space(uint32_t c)
{
    if (likely(c < 128)) {
        return unicode_is_space_ascii(c);
    } else {
        return unicode_is_space_non_ascii(c);
    }
}

/* cross-module prototypes */
BOOL JS_HasException(JSContext *ctx);
BOOL JS_HasProperty(JSContext *ctx, JSValue obj, JSValue prop);
BOOL JS_IsArray(JSContext *ctx, JSValue obj);
BOOL JS_IsBytecode(const uint8_t *buf, size_t buf_len);
BOOL JS_IsError(JSContext *ctx, JSValue val);
BOOL JS_IsFunction(JSContext *ctx, JSValue val);
BOOL JS_IsFunctionObject(JSContext *ctx, JSValue val);
BOOL JS_IsNumber(JSContext *ctx, JSValue val);
BOOL JS_IsNumericProperty(JSContext *ctx, JSValue val);
BOOL JS_IsObject(JSContext *ctx, JSValue val);
BOOL JS_IsPrimitive(JSContext *ctx, JSValue val);
BOOL JS_IsString(JSContext *ctx, JSValue val);
BOOL gc_mb_is_marked(JSValue val);
BOOL int64_is_short_int(int64_t val);
BOOL is_ascii_string(const char *buf, size_t len);
BOOL is_digit(int c);
BOOL is_label(JSParseState *s);
BOOL is_line_terminator(uint32_t c);
BOOL is_num_string(JSContext *ctx, int32_t *pval, JSValue val);
BOOL is_regexp_allowed(int tok);
BOOL is_utf8_left_surrogate(const uint8_t *p);
BOOL is_utf8_right_surrogate(const uint8_t *p);
BOOL is_valid_len4_utf8(const uint8_t *buf);
BOOL is_word_char(uint32_t c);
BOOL js_strict_eq(JSContext *ctx, JSValue op1, JSValue op2);
BOOL js_string_eq(JSContext *ctx, JSValue val1, JSValue val2);
BOOL label_is_none(JSValue label);
BOOL may_drop_result(JSParseState *s, int parse_flags);
BOOL mtag_has_references(int mtag);
BOOL re_need_check_adv_and_capture_init(BOOL *pneed_capture_init, const uint8_t *bc_buf, int bc_buf_len);
BlockEnv *push_break_entry(JSParseState *s, JSValue label_name, JSValue label_break, JSValue label_cont, int drop_count);
JSByteArray *js_alloc_byte_array(JSContext *ctx, int size);
JSContext *JS_NewContext(void *mem_start, size_t mem_size, const JSSTDLibraryDef *stdlib_def);
JSContext *JS_NewContext2(void *mem_start, size_t mem_size, const JSSTDLibraryDef *stdlib_def, BOOL prepare_compilation);
JSFunctionBytecode *js_alloc_function_bytecode(JSContext *ctx);
JSObject *JS_NewObjectProtoClass1(JSContext *ctx, JSValue proto, int class_id, int extra_size);
JSObject *get_typed_array(JSContext *ctx, JSValue val);
JSObject *js_get_array(JSContext *ctx, JSValue obj);
JSObject *js_get_object_class(JSContext *ctx, JSValue val, int class_id);
JSProperty *find_own_property(JSContext *ctx, JSObject *p, JSValue prop);
JSProperty *js_create_property(JSContext *ctx, JSValue obj, JSValue prop);
JSRegExp *js_get_regexp(JSContext *ctx, JSValue obj);
JSString *get_string_ptr(JSContext *ctx, JSStringCharBuf *buf, JSValue val);
JSString *js_alloc_string(JSContext *ctx, uint32_t buf_len);
JSValue *JS_AddGCRef(JSContext *ctx, JSGCRef *ref);
JSValue *JS_PushGCRef(JSContext *ctx, JSGCRef *ref);
JSValue *js_value_to_pval(JSContext *ctx, JSValue val);
JSValue JS_Call(JSContext *ctx, int call_flags);
JSValue JS_ConcatString(JSContext *ctx, JSValue val1, JSValue val2);
JSValue JS_DefinePropertyGetSet(JSContext *ctx, JSValue obj, JSValue prop, JSValue getter, JSValue setter, int flags);
JSValue JS_DefinePropertyInternal(JSContext *ctx, JSValue obj, JSValue prop, JSValue val, JSValue setter, int flags);
JSValue JS_DefinePropertyValue(JSContext *ctx, JSValue obj, JSValue prop, JSValue val);
JSValue JS_DeleteProperty(JSContext *ctx, JSValue this_obj, JSValue prop);
JSValue JS_Eval(JSContext *ctx, const char *input, size_t input_len, const char *filename, int eval_flags);
JSValue JS_GetException(JSContext *ctx);
JSValue JS_GetGlobalObject(JSContext *ctx);
JSValue JS_GetProperty(JSContext *ctx, JSValue obj, JSValue prop);
JSValue JS_GetPropertyInternal(JSContext *ctx, JSValue obj, JSValue prop, BOOL allow_tail_call);
JSValue JS_GetPropertyStr(JSContext *ctx, JSValue this_obj, const char *str);
JSValue JS_GetPropertyUint32(JSContext *ctx, JSValue obj, uint32_t idx);
JSValue JS_LoadBytecode(JSContext *ctx, const uint8_t *buf);
JSValue JS_MakeUniqueString(JSContext *ctx, JSValue val);
JSValue JS_NewArray(JSContext *ctx, int initial_len);
JSValue JS_NewCFunctionParams(JSContext *ctx, int func_idx, JSValue params);
JSValue JS_NewDate(JSContext *ctx, double epoch_ms);
JSValue JS_NewFloat64(JSContext *ctx, double d);
JSValue JS_NewInt32(JSContext *ctx, int32_t val);
JSValue JS_NewInt64(JSContext *ctx, int64_t val);
JSValue JS_NewObject(JSContext *ctx);
JSValue JS_NewObjectClass(JSContext *ctx, int class_id, int extra_size);
JSValue JS_NewObjectClassUser(JSContext *ctx, int class_id);
JSValue JS_NewObjectPrealloc(JSContext *ctx, int n);
JSValue JS_NewObjectProtoClass(JSContext *ctx, JSValue proto, int class_id, int extra_size);
JSValue JS_NewShortInt(int32_t val);
JSValue JS_NewString(JSContext *ctx, const char *buf);
JSValue JS_NewStringChar(uint32_t c);
JSValue JS_NewStringLen(JSContext *ctx, const char *buf, size_t len);
JSValue JS_NewUint32(JSContext *ctx, uint32_t val);
JSValue JS_Parse(JSContext *ctx, const char *input, size_t input_len, const char *filename, int eval_flags);
JSValue JS_Parse2(JSContext *ctx, JSValue source_str, const char *input, size_t input_len, const char *filename, int eval_flags);
JSValue JS_PopGCRef(JSContext *ctx, JSGCRef *ref);
JSValue JS_Run(JSContext *ctx, JSValue val);
JSValue JS_SetPropertyInternal(JSContext *ctx, JSValue this_obj, JSValue prop, JSValue val, BOOL allow_tail_call);
JSValue JS_SetPropertyStr(JSContext *ctx, JSValue this_obj, const char *str, JSValue val);
JSValue JS_SetPropertyUint32(JSContext *ctx, JSValue this_obj, uint32_t idx, JSValue val);
JSValue JS_Throw(JSContext *ctx, JSValue obj);
JSValue JS_ThrowOutOfMemory(JSContext *ctx);
JSValue JS_ThrowTypeErrorNotAnObject(JSContext *ctx);
JSValue JS_ToPrimitive(JSContext *ctx, JSValue val, int hint);
JSValue JS_ToPropertyKey(JSContext *ctx, JSValue val);
JSValue JS_ToString(JSContext *ctx, JSValue val);
JSValue JS_ToStringCheckObject(JSContext *ctx, JSValue val);
JSValue __JS_NewFloat64(JSContext *ctx, double d);
JSValue __js_poll_interrupt(JSContext *ctx);
JSValue add_global_var(JSContext *ctx, JSValue prop, BOOL define_flag);
JSValue find_atom(JSContext *ctx, int *pidx, const JSValueArray *arr, int len, JSValue val);
JSValue get_ext_var_name(JSParseState *s, int var_idx);
JSValue get_special_prop(JSContext *ctx, JSValue val);
JSValue get_var_ref(JSContext *ctx, JSValue *pfirst_var_ref, JSValue *pval);
JSValue js_alloc_float64(JSContext *ctx, double d);
JSValue js_array_buffer_alloc(JSContext *ctx, uint64_t len);
JSValue js_array_buffer_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_array_buffer_get_byteLength(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_array_concat(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_array_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_array_every(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int special);
JSValue js_array_get_length(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_array_indexOf(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int is_lastIndexOf);
JSValue js_array_isArray(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_array_join(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_array_pop(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_array_push(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int is_unshift);
JSValue js_array_reduce(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int special);
JSValue js_array_reverse(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_array_set_length(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_array_shift(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_array_slice(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_array_sort(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_array_splice(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_array_toString(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_boolean_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_byte_array_to_string(JSContext *ctx, JSValue val, int len, BOOL is_ascii);
JSValue js_call_constructor_start(JSContext *ctx, JSValue func);
JSValue js_closure(JSContext *ctx, JSValue bfunc, JSValue *fp);
JSValue js_compile_regexp(JSContext *ctx, JSValue pattern, JSValue flags);
JSValue js_date_valueOf(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_dtoa2(JSContext *ctx, double d, int radix, int n_digits, int flags);
JSValue js_error_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int magic);
JSValue js_error_get_message(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int magic);
JSValue js_error_toString(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_find_class_name(JSContext *ctx, int class_id);
JSValue js_for_of_next(JSContext *ctx);
JSValue js_for_of_start(JSContext *ctx, BOOL is_for_in);
JSValue js_function_apply(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_function_bind(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_function_bound(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, JSValue params);
JSValue js_function_call(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_function_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_function_get_length_name(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int is_name);
JSValue js_function_get_length_name1(JSContext *ctx, JSValue *this_val, int is_name, JSFunctionBytecode **pb);
JSValue js_function_get_prototype(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_function_set_prototype(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_function_toString(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_get_atom(JSContext *ctx, int a);
JSValue js_global_eval(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_global_isFinite(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_global_isNaN(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_json_parse(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_json_stringify(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_math_atan2(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_math_clz32(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_math_imul(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_math_min_max(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int magic);
JSValue js_math_pow(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_math_random(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_new_c_function_proto(JSContext *ctx, int func_idx, JSValue proto, BOOL has_params, JSValue params);
JSValue js_number_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_number_parseFloat(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_number_parseInt(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_number_toExponential(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_number_toFixed(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_number_toPrecision(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_number_toString(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_object_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_object_create(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_object_defineProperty(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_object_getPrototypeOf(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_object_hasOwnProperty(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_object_keys(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_object_setPrototypeOf(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_object_toString(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_operator_in(JSContext *ctx);
JSValue js_operator_instanceof(JSContext *ctx);
JSValue js_operator_typeof(JSContext *ctx, JSValue val);
JSValue js_parse_json(JSParseState *s);
JSValue js_parse_pop_val(JSParseState *s);
JSValue js_parse_regexp(JSParseState *s, int re_flags);
JSValue js_parse_string(JSParseState *s, uint32_t *ppos, int sep);
JSValue js_regexp_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_regexp_exec(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int magic);
JSValue js_regexp_get_flags(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_regexp_get_lastIndex(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_regexp_get_source(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_regexp_set_lastIndex(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_resize_byte_array(JSContext *ctx, JSValue val, int new_size);
JSValue js_resize_value_array(JSContext *ctx, JSValue val, int new_size);
JSValue js_resize_value_array2(JSContext *ctx, JSValue val, int new_size, int prop_base);
JSValue js_set_prototype_internal(JSContext *ctx, JSValue obj, JSValue proto);
JSValue js_strict_eq_slow(JSContext *ctx, BOOL is_neq);
JSValue js_string_charAt(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int magic);
JSValue js_string_concat(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_string_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_string_fromCharCode(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int is_fromCodePoint);
JSValue js_string_get_length(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_string_indexOf(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int lastIndexOf);
JSValue js_string_match(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_string_repeat(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_string_replace(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int is_replaceAll);
JSValue js_string_search(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_string_set_length(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_string_slice(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_string_split(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_string_substring(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_string_toLowerCase(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int to_lower);
JSValue js_string_toString(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_string_trim(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int magic);
JSValue js_sub_string(JSContext *ctx, JSValue val, int start, int end);
JSValue js_sub_string_utf8(JSContext *ctx, JSValue val, uint32_t start0, uint32_t end0);
JSValue js_to_short_float(double d);
JSValue js_typed_array_base_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_typed_array_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int magic);
JSValue js_typed_array_constructor_obj(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int magic);
JSValue js_typed_array_get_length(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int magic);
JSValue js_typed_array_set(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_typed_array_subarray(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv);
JSValue js_value_from_pval(JSContext *ctx, JSValue *pval);
JSValue new_label(JSParseState *s);
JSValue parse_stack_alloc(JSParseState *s, JSValue val);
JSValue reloc_c_func_name(JSContext *ctx, JSValue val);
JSValue stdlib_init_class(JSContext *ctx, const JSROMClass *class_def);
JSValue string_buffer_pop(JSContext *ctx, StringBuffer *s);
JSValueArray *js_alloc_props(JSContext *ctx, int n);
JSValueArray *js_alloc_value_array(JSContext *ctx, int init_base, int new_size);
JS_BOOL JS_IsExceptionOrTailCall(JSValue v);
__maybe_unused int js_string_byte_len(JSContext *ctx, JSValue val);
__maybe_unused void JS_DumpUniqueStrings(JSContext *ctx);
__maybe_unused void dump_byte_code(JSContext *ctx, JSFunctionBytecode *b);
__maybe_unused void dump_string_pos_cache(JSContext *ctx);
__maybe_unused void js_putchar(JSContext *ctx, uint8_t c);
__maybe_unused void lre_dump_bytecode(const uint8_t *buf, int buf_len);
const char *JS_ToCString(JSContext *ctx, JSValue val, JSCStringBuf *buf);
const char *JS_ToCStringLen(JSContext *ctx, size_t *plen, JSValue val, JSCStringBuf *buf);
const char *get_func_name(JSContext *ctx, JSValue func_obj, JSCStringBuf *str_buf, JSFunctionBytecode **pb);
const char *get_mtag_name(unsigned int mtag);
double js_fmax(double a, double b);
double js_fmin(double a, double b);
double js_get_short_float(JSValue v);
double js_math_fround(double a);
double js_math_sign(double a);
int JS_GetClassID(JSContext *ctx, JSValue val);
int JS_PrepareBytecode64to32(JSContext *ctx, JSBytecodeHeader32 *hdr, const uint8_t **pdata_buf, uint32_t *pdata_len, JSValue eval_code);
int JS_RelocateBytecode(JSContext *ctx, uint8_t *buf, uint32_t buf_len);
int JS_RelocateBytecode2(JSContext *ctx, JSBytecodeHeader *hdr, uint8_t *buf, uint32_t buf_len, uintptr_t new_base_addr, BOOL update_atoms);
int JS_StackCheck(JSContext *ctx, uint32_t len);
int JS_ToBool(JSContext *ctx, JSValue val);
int JS_ToIndex(JSContext *ctx, uint64_t *plen, JSValue val);
int JS_ToInt32(JSContext *ctx, int *pres, JSValue val);
int JS_ToInt32Clamp(JSContext *ctx, int *pres, JSValue val, int min, int max, int min_offset);
int JS_ToInt32Internal(JSContext *ctx, int *pres, JSValue val, BOOL sat_flag);
int JS_ToInt32Sat(JSContext *ctx, int *pres, JSValue val);
int JS_ToNumber(JSContext *ctx, double *pres, JSValue val);
int JS_ToUint32(JSContext *ctx, uint32_t *pres, JSValue val);
int JS_ToUint8Clamp(JSContext *ctx, int *pres, JSValue val);
int add_ext_var(JSParseState *s, JSValue name, int decl);
int add_func_ext_var(JSParseState *s, JSValue func, JSValue name, int decl);
int add_var(JSParseState *s, JSValue name);
int check_circular_ref(JSContext *ctx, JSValue *stack_top, JSValue val);
int check_free_mem(JSContext *ctx, JSValue *stack_bottom, uint32_t size);
int convert_mblock_64to32(void *ptr1, const void *ptr);
int cpool_add(JSParseState *s, JSValue val);
int define_var(JSParseState *s, JSVarRefKindEnum *pvar_kind, JSValue name);
int expand_short_float(JSContext *ctx, JSValue *pval);
int expand_short_floats(JSContext *ctx);
int find_ext_var(JSParseState *s, JSValue name);
int find_func_ext_var(JSParseState *s, JSValue func, JSValue name);
int find_func_var(JSContext *ctx, JSValue func, JSValue name);
int find_line_col(int *pcol_num, JSFunctionBytecode *b, uint32_t pc);
int find_var(JSParseState *s, JSValue name);
int gc_compact_heap_64to32(JSContext *ctx);
int get_class_atom(JSParseState *s, BOOL inclass);
int get_first_free(JSValueArray *arr);
int get_line_col(int *pcol_num, const uint8_t *buf, size_t len);
int get_line_col_delta(int *pcol_num, const uint8_t *buf, int pos1, int pos2);
int get_mblock_size(const void *ptr);
int get_mblock_size_32(const void *ptr);
int get_pc2line_hoisted_code_len(const uint8_t *buf, size_t buf_len);
int get_prev_opcode(JSParseState *s);
int get_prop_hash_size_log2(int prop_count);
int get_short_string(uint8_t *buf, JSValue val);
int is_ident_first(int c);
int is_ident_next(int c);
int is_num(int c);
int js_array_resize(JSContext *ctx, JSValue *this_val, int new_len);
int js_array_sort_cmp(size_t i1, size_t i2, void *opaque);
int js_atod1(JSContext *ctx, double *pres, JSValue val, int radix, int flags);
int js_eq_get_type(JSContext *ctx, JSValue val);
int js_get_length32(JSContext *ctx, uint32_t *pres, JSValue obj);
int js_get_mtag(void *ptr);
int js_is_numeric_string(JSContext *ctx, JSValue val);
int js_parse_assign_expr(JSParseState *s, int state, int parse_flags);
int js_parse_block(JSParseState *s, int state, int dummy_param);
int js_parse_cond_expr(JSParseState *s, int state, int parse_flags);
int js_parse_escape(const uint8_t *buf, size_t *plen);
int js_parse_expr_binary(JSParseState *s, int state, int parse_flags);
int js_parse_expr_comma(JSParseState *s, int state, int parse_flags);
int js_parse_json_value(JSParseState *s, int state, int dummy_param);
int js_parse_logical_and_or(JSParseState *s, int state, int parse_flags);
int js_parse_postfix_expr(JSParseState *s, int state, int parse_flags);
int js_parse_property_name(JSParseState *s, JSValue *pname);
int js_parse_skip_parens_token(JSParseState *s);
int js_parse_statement(JSParseState *s, int state, int dummy_param);
int js_parse_unary(JSParseState *s, int state, int parse_flags);
int js_skip_parens(JSParseState *s, JSValue *pfunc_name);
int js_string_compare(JSContext *ctx, JSValue val1, JSValue val2);
int js_string_concat_subst(JSContext *ctx, StringBuffer *b, JSValue *str, JSValue *rep, uint32_t pos, uint32_t end_of_match, JSValue *capture_buf, uint32_t captures_len, JSValue *needle);
int js_string_indexof(JSContext *ctx, JSValue str, JSValue needle, int start, int str_len, int needle_len);
int js_string_len(JSContext *ctx, JSValue val);
int js_thisNumberValue(JSContext *ctx, double *pres, JSValue val);
int js_to_quoted_string(JSContext *ctx, StringBuffer *b, JSValue str);
int js_update_props(JSContext *ctx, JSValue obj);
int js_vsnprintf(char *buf, size_t buf_size, const char *fmt, va_list ap);
int lre_canonicalize(uint32_t c);
int lre_exec(JSContext *ctx, JSValue capture_buf, JSValue byte_code, JSValue str, int cindex);
int lre_get_alloc_count(const uint8_t *bc_buf);
int lre_get_capture_count(const uint8_t *bc_buf);
int lre_get_flags(const uint8_t *bc_buf);
int parse_digits(const uint8_t **pp);
int range_compress(uint8_t *tab, int len);
int range_sort_cmp(size_t i1, size_t i2, void *opaque);
int re_compute_register_count(JSParseState *s, uint8_t *bc_buf, int bc_buf_len);
int re_emit_goto(JSParseState *s, int op, uint32_t val);
int re_emit_goto_u8(JSParseState *s, int op, uint32_t arg, uint32_t val);
int re_emit_goto_u8_u32(JSParseState *s, int op, uint32_t arg0, uint32_t arg1, uint32_t val);
int re_emit_op_u32(JSParseState *s, int op, uint32_t val);
int re_is_char(const uint8_t *buf, int start, int end);
int re_parse_alternative(JSParseState *s, int state, int dummy_param);
int re_parse_disjunction(JSParseState *s, int state, int dummy_param);
int skip_spaces(const char *p1);
int string_buffer_concat(JSContext *ctx, StringBuffer *s, JSValue val2);
int string_buffer_concat_str(JSContext *ctx, StringBuffer *s, JSValue val2);
int string_buffer_concat_utf16(JSContext *ctx, StringBuffer *s, JSValue str, uint32_t start, uint32_t end);
int string_buffer_concat_utf8(JSContext *ctx, StringBuffer *s, JSValue str, uint32_t start, uint32_t end);
int string_buffer_push(JSContext *ctx, StringBuffer *s, int len);
int string_buffer_putc(JSContext *ctx, StringBuffer *s, int c);
int string_buffer_puts(JSContext *ctx, StringBuffer *s, const char *str);
int string_get_cp(const uint8_t *p);
int string_getc(JSContext *ctx, JSValue str, uint32_t utf16_pos);
int string_getcp(JSContext *ctx, JSValue str, uint32_t utf16_pos, BOOL is_codepoint);
int32_t get_sgolomb(const uint8_t *buf, uint32_t buf_len, uint32_t *pindex);
no_inline JSValue js_add_slow(JSContext *ctx);
no_inline JSValue js_binary_arith_slow(JSContext *ctx, OPCodeEnum op);
no_inline JSValue js_binary_logic_slow(JSContext *ctx, OPCodeEnum op);
no_inline JSValue js_eq_slow(JSContext *ctx, BOOL is_neq);
no_inline JSValue js_not_slow(JSContext *ctx);
no_inline JSValue js_post_inc_slow(JSContext *ctx, OPCodeEnum op);
no_inline JSValue js_relational_slow(JSContext *ctx, OPCodeEnum op);
no_inline JSValue js_unary_arith_slow(JSContext *ctx, OPCodeEnum op);
size_t js_parse_regexp_flags(int *pre_flags, const uint8_t *buf);
size_t js_regexp_flags_str(char *buf, int re_flags);
uint32_t get_bit(const uint8_t *buf, uint32_t index);
uint32_t get_bits(const uint8_t *buf, uint32_t buf_len, uint32_t index, int n);
uint32_t get_bits_slow(const uint8_t *buf, uint32_t index, int n);
uint32_t get_ugolomb(const uint8_t *buf, uint32_t buf_len, uint32_t *pindex);
uint32_t js_string_convert_pos(JSContext *ctx, JSValue val, uint32_t pos, StringPosTypeEnum pos_type);
uint32_t js_string_utf16_to_utf8_pos(JSContext *ctx, JSValue val, uint32_t utf16_pos);
uint32_t js_string_utf8_to_utf16_pos(JSContext *ctx, JSValue val, uint32_t utf8_pos);
uint32_t val_to_offset(JSContext *ctx, JSValue val);
uint64_t rotl64(uint64_t a, int n);
uint64_t xorshift64star(uint64_t *pstate);
uint8_t *get_byte_code(JSParseState *s);
void *JS_GetContextOpaque(JSContext *ctx);
void *JS_GetOpaque(JSContext *ctx, JSValue val);
void *js_malloc(JSContext *ctx, uint32_t size, int mtag);
void *js_mallocz(JSContext *ctx, uint32_t size, int mtag);
void *js_shrink(JSContext *ctx, void *ptr, uint32_t new_size);
void JS_DeleteGCRef(JSContext *ctx, JSGCRef *ref);
void JS_DumpMemory(JSContext *ctx, BOOL is_long);
void JS_DumpValue(JSContext *ctx, const char *str, JSValue val);
void JS_DumpValueF(JSContext *ctx, const char *str, JSValue val, int flags);
void JS_FreeContext(JSContext *ctx);
void JS_GC(JSContext *ctx);
void JS_GC2(JSContext *ctx, BOOL keep_atoms);
void JS_PrepareBytecode(JSContext *ctx, JSBytecodeHeader *hdr, const uint8_t **pdata_buf, uint32_t *pdata_len, JSValue eval_code);
void JS_PrintValue(JSContext *ctx, JSValue val);
void JS_PrintValueF(JSContext *ctx, JSValue val, int flags);
void JS_PushArg(JSContext *ctx, JSValue val);
void JS_SetContextOpaque(JSContext *ctx, void *opaque);
void JS_SetInterruptHandler(JSContext *ctx, JSInterruptHandler *interrupt_handler);
void JS_SetLogFunc(JSContext *ctx, JSWriteFunc *write_func);
void JS_SetOpaque(JSContext *ctx, JSValue val, void *opaque);
void JS_SetRandomSeed(JSContext *ctx, uint64_t seed);
void add_interval_intersect(JSParseState *s, uint32_t start, uint32_t end, uint32_t start1, uint32_t end1, int offset);
void bc_reloc_value(BCRelocState *s, JSValue *pval);
void build_backtrace(JSContext *ctx, JSValue error_obj, const char *filename, int line_num, int col_num, int skip_level);
void compute_stack_size(JSParseState *s, JSValue *pfunc);
void compute_stack_size_push(JSParseState *s, JSByteArray *arr, uint8_t *explore_tab, uint32_t pos, int stack_len);
void convert_ext_vars_to_local_vars(JSParseState *s);
void convert_ext_vars_to_local_vars_bytecode(JSParseState *s, uint8_t *byte_code, int byte_code_len, int var_start, const ConvertVarEntry *cvt_tab, int tab_len);
void define_hoisted_functions(JSParseState *s, BOOL is_eval);
void dummy_write_func(void *opaque, const void *buf, size_t buf_len);
void dump_pc2line(void);
void dump_regexp(JSContext *ctx, JSObject *p);
void dump_string(JSContext *ctx, int sep, const uint8_t *buf, size_t len, int flags);
void emit_break(JSParseState *s, JSValue label_name, int is_cont);
void emit_claim_size(JSParseState *s, int n);
void emit_goto(JSParseState *s, int opcode, JSValue *plabel);
void emit_insert(JSParseState *s, int pos, int n);
void emit_label(JSParseState *s, JSValue *plabel);
void emit_label_pos(JSParseState *s, JSValue *plabel, int pos);
void emit_op(JSParseState *s, uint8_t op);
void emit_op_param(JSParseState *s, uint8_t op, uint32_t param, JSSourcePos source_pos);
void emit_op_pos(JSParseState *s, uint8_t op, JSSourcePos source_pos);
void emit_pc2line(JSParseState *s, JSSourcePos pos);
void emit_push_short_int(JSParseState *s, int val);
void emit_return(JSParseState *s, BOOL hasval, JSSourcePos source_pos);
void emit_u16(JSParseState *s, uint16_t val);
void emit_u32(JSParseState *s, uint32_t val);
void emit_u8(JSParseState *s, uint8_t val);
void emit_var(JSParseState *s, int opcode, int var_idx, JSSourcePos source_pos);
void gc_compact_heap(JSContext *ctx);
void gc_mark(GCMarkState *s, JSValue val);
void gc_mark_all(JSContext *ctx, BOOL keep_atoms);
void gc_mark_flush(GCMarkState *s);
void gc_mark_root(GCMarkState *s, JSValue val);
void gc_thread_block(JSContext *ctx, void *ptr);
void gc_thread_pointer(JSContext *ctx, JSValue *pval);
void gc_update_threaded_pointers(JSContext *ctx, void *ptr, void *new_ptr);
void get_lvalue(JSParseState *s, int *popcode, int *pvar_idx, JSSourcePos *psource_pos, BOOL keep);
void get_pc2line(int *pline_num, int *pcol_num, const uint8_t *buf, uint32_t buf_len, uint32_t *pindex, BOOL has_column);
void js_array_sort_swap(size_t i1, size_t i2, void *opaque);
void js_compact_props(JSContext *ctx, JSObject *p);
void js_dump_array(JSContext *ctx, JSValueArray *arr, int len);
void js_dump_error(JSContext *ctx, JSObject *p);
void js_dump_float64(JSContext *ctx, double d);
void js_dump_object(JSContext *ctx, JSObject *p, int flags);
void js_emit_delete(JSParseState *s);
void js_emit_push_const(JSParseState *s, JSValue val);
void js_emit_push_number(JSParseState *s, double d);
void js_free(JSContext *ctx, void *ptr);
void js_parse_assign_expr2(JSParseState *s, int parse_flags);
void js_parse_call(JSParseState *s, ParseExprFuncEnum func_idx, int param);
void js_parse_error_mem(JSParseState *s);
void js_parse_error_stack_overflow(JSParseState *s);
void js_parse_expect(JSParseState *s, int ch);
void js_parse_expect1(JSParseState *s, int ch);
void js_parse_expect_semi(JSParseState *s);
void js_parse_expr(JSParseState *s);
void js_parse_expr2(JSParseState *s, int parse_flags);
void js_parse_expr_paren(JSParseState *s);
void js_parse_function(JSParseState *s);
void js_parse_function_decl(JSParseState *s, JSParseFunctionEnum func_type, JSValue func_name);
void js_parse_get_pos(JSParseState *s, JSParsePos *sp);
void js_parse_ident(JSParseState *s, JSToken *token, uint32_t *ppos, int c);
void js_parse_local_functions(JSParseState *s, JSValue *pfunc);
void js_parse_program(JSParseState *s);
void js_parse_push_val(JSParseState *s, JSValue val);
void js_parse_regexp_token(JSParseState *s, uint32_t *ppos);
void js_parse_seek_token(JSParseState *s, const JSParsePos *sp);
void js_parse_source_element(JSParseState *s);
void js_parse_var(JSParseState *s, BOOL in_accepted);
void js_rehash_props(JSContext *ctx, JSObject *p, BOOL gc_rehash);
void js_reverse_val(JSValue *tab, int n);
void js_shrink_byte_array(JSContext *ctx, JSValue *pval, int new_size);
void js_shrink_value_array(JSContext *ctx, JSValue *pval, int new_size);
void js_skip_expr(JSParseState *s);
void js_vprintf(JSWriteFunc *write_func, void *opaque, const char *fmt, va_list ap);
void next_token(JSParseState *s);
void pad(JSWriteFunc *write_func, void *opaque, char c, int width, int len);
void pc2line_put_bits(JSParseState *s, int n, uint32_t bits);
void pc2line_put_bits_short(JSParseState *s, int n, uint32_t bits);
void pop_break_entry(JSParseState *s);
void put_lvalue(JSParseState *s, int opcode, int var_idx, JSSourcePos source_pos, PutLValueEnum special);
void put_sgolomb(JSParseState *s, int32_t v1);
void put_ugolomb(JSParseState *s, uint32_t v);
void put_var(JSParseState *s, JSVarRefKindEnum var_kind, int var_idx, JSSourcePos source_pos);
void range_sort_swap(size_t i1, size_t i2, void *opaque);
void re_emit_char(JSParseState *s, int c);
void re_emit_op(JSParseState *s, int op);
void re_emit_op_u16(JSParseState *s, int op, uint32_t val);
void re_emit_op_u8(JSParseState *s, int op, uint32_t val);
void re_emit_range_base(JSParseState *s, int c);
void re_emit_range_base1(JSParseState *s, const uint16_t *tab, int n);
void re_parse_char_class(JSParseState *s);
void re_parse_expect(JSParseState *s, int c);
void re_parse_quantifier(JSParseState *s, int last_atom_start, int last_capture_count);
void re_range_optimize(JSParseState *s, int range_start, BOOL invert);
void remove_last_op(JSParseState *s);
void reset_parse_state(JSParseState *s, uint32_t input_pos, JSValue cur_func);
void resolve_var_refs(JSParseState *s, JSValue *pfunc, JSValue *pparent_func);
void set_eval_ret_undefined(JSParseState *s);
void set_free_block(void *ptr, uint32_t size);
void snprintf_write_func(void *opaque, const void *buf, size_t buf_len);
void stdlib_init(JSContext *ctx, const JSValueArray *arr);
void __js_printf_like(2, 3) js_printf(JSContext *ctx, const char *fmt, ...);
int js_vsnprintf(char *buf, size_t buf_size, const char *fmt, va_list ap);
int __maybe_unused __js_printf_like(3, 4) js_snprintf(char *buf, size_t buf_size, const char *fmt, ...);
void __attribute__((format(printf, 2, 3), noreturn)) js_parse_error(JSParseState *s, const char *fmt, ...);
void js_parse_error_stack_overflow(JSParseState *s);
void js_parse_error_mem(JSParseState *s);
BOOL label_is_none(JSValue label);


extern const char *js_mtag_name[JS_MTAG_COUNT];
extern const JSOpCode opcode_info[OP_COUNT];
extern const REOpCode reopcode_info[REOP_COUNT];

#endif /* MQUICKJS_INTERNAL_H */
